base_url = "https://athletedecoded.com"
title = "Kahlia Hogg CV"
description = "Kahlia Hogg CV"

compile_sass = true
generate_feed = true
build_search_index = true
taxonomies = [
  { name = "tags", feed = true },
]

[markdown]
highlight_code = true
highlight_theme = "OneHalfLight"

[extra]
first_name = "Kahlia"
last_name = "Hogg"
address = "Durham, NC"
email = "kahlia.hogg@gmail.com"
github = "athletedecoded"
favicon = "/favicon.ico"
avatar = "/media/headshot.jpg"

show_about = true
show_stack = true
show_projects = true
show_publications = false
show_experience = true
show_education = true
show_blog = false
